data:
  base_dir: data
  daily_dir: data/nse_daily
  eod_tol: 0.001
  hourly_dir: data/nse_hourly
  intraday_universe_list: ind_nifty200list.csv
  overlap_days: 2
  update_hourly_eod: false
  update_hourly_intraday: false
  workers: 8
event_finder:
  gold_trigger_tol: 0.002
  run_gold_event_finder: true
  run_stock_event_finder: true
  show_gold_events: true
  show_stock_events: true
market:
  close: '15:30'
  open: 09:15
  trading_days_only: true
  tz_offset_minutes: 330
moneycontrol_run_times:
- 08:45
output:
  auto_open: false
  dir: data/screener_output
  export_dir: C:/DATA/CODE/Stocks/EventFinder/Results
  notify: true
  watchlist_prefix:
  - NSE:NIFTY50-INDEX
  - BSE:SENSEX-INDEX
run_times:
- 09:30
- '10:30'
- '11:30'
- '12:30'
- '13:30'
- '14:30'
- '16:00'
screener:
  big_mult: 2.0
  left: 2
  right: 3
  target: 20
  tol: 0.005
telegram:
  bot_token: 8952946545:AAFLYnADSfcF7PEwkpLPh-0oOj4Md1bIExE
  chat_id: '406879558'
  enable_telegram: true
